/* ------------------------------------------------------------------ */
/*  Monthly clinic statement PDF — itemized bill of every case on a     */
/*  statement, drawn as vector text with jsPDF (same engine as the Rx   */
/*  PDF's vector path, dynamically imported so it never bloats the      */
/*  main bundle). Latin-1 only, like the Rx sheet's built-in fonts —    */
/*  amounts and dates are always ASCII; names outside WinAnsi degrade   */
/*  to jsPDF's replacement glyphs, acceptable for an internal bill.     */
/* ------------------------------------------------------------------ */

const fmt = (n) =>
  `${Number(n).toLocaleString("en", { minimumFractionDigits: 0, maximumFractionDigits: 3 })} OMR`;

const monthLabel = (isoMonth) =>
  new Date(isoMonth + "T00:00:00").toLocaleDateString("en-GB", { month: "long", year: "numeric" });

export async function downloadStatementPdf({ lab, clinic, statement, cases, paidSoFar }) {
  const { jsPDF } = await import("jspdf");
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const W = 210;
  const M = 16;
  let y = 20;

  const line = (weight, size, text, x = M, align = "left") => {
    doc.setFont("helvetica", weight);
    doc.setFontSize(size);
    doc.text(String(text), x, y, { align });
  };

  // Header
  line("bold", 16, lab?.name ?? "Dental Laboratory");
  y += 6;
  line("normal", 9, `Monthly statement — ${monthLabel(statement.month)}`);
  doc.setTextColor(100);
  y += 5;
  line("normal", 8, [lab?.contact, lab?.email].filter(Boolean).join("  ·  "));
  doc.setTextColor(0);
  y += 9;

  line("bold", 10, "Billed to");
  y += 5;
  line("normal", 10, clinic?.name ?? "Clinic");
  y += 5;
  if (clinic?.email) {
    doc.setTextColor(100);
    line("normal", 8, clinic.email);
    doc.setTextColor(0);
    y += 5;
  }
  y += 4;

  // Table header
  const cols = { date: M, patient: M + 26, type: M + 86, units: M + 152, amount: W - M };
  const headerRow = () => {
    doc.setFillColor(241, 245, 249);
    doc.rect(M - 2, y - 4.5, W - 2 * M + 4, 7, "F");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(8);
    doc.text("Completed", cols.date, y);
    doc.text("Patient", cols.patient, y);
    doc.text("Work", cols.type, y);
    doc.text("Units", cols.units, y, { align: "right" });
    doc.text("Amount", cols.amount, y, { align: "right" });
    y += 6;
  };
  headerRow();

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8.5);
  for (const c of cases) {
    if (y > 270) {
      doc.addPage();
      y = 20;
      headerRow();
      doc.setFont("helvetica", "normal");
      doc.setFontSize(8.5);
    }
    const rest = c.prescription?.restorations;
    const cancelled = c.cancelStatus === "cancelled";
    let label = rest?.length
      ? rest.map((r) => r.category).join(", ")
      : c.prescription?.category ?? "—";
    if (cancelled) label = `Cancellation fee — ${label}`;
    const units = rest?.length
      ? rest.reduce((n, r) => n + (r.teeth?.length || 1), 0)
      : c.prescription?.teeth?.length || 1;
    const completed = c.completedAtLabel ?? "";
    doc.text(completed, cols.date, y);
    doc.text(doc.splitTextToSize(c.patientName ?? "", 56)[0] ?? "", cols.patient, y);
    doc.text(doc.splitTextToSize(label, 62)[0] ?? "", cols.type, y);
    doc.text(String(units), cols.units, y, { align: "right" });
    doc.text(fmt(cancelled ? c.cancellationFee ?? 0 : c.totalPrice ?? 0), cols.amount, y, { align: "right" });
    y += 5.5;
  }

  // Totals
  y += 3;
  doc.setDrawColor(226, 232, 240);
  doc.line(M, y, W - M, y);
  y += 6;
  line("bold", 10, "Total due", cols.units - 30);
  line("bold", 10, fmt(statement.total), cols.amount, "right");
  if (paidSoFar > 0) {
    y += 6;
    line("normal", 9, "Paid to date", cols.units - 30);
    line("normal", 9, fmt(paidSoFar), cols.amount, "right");
    y += 6;
    line("bold", 10, "Balance", cols.units - 30);
    line("bold", 10, fmt(Math.max(0, statement.total - paidSoFar)), cols.amount, "right");
  }

  y += 12;
  doc.setTextColor(100);
  line("normal", 7.5, "Generated by Dr-Crown (dr-crown.com). Please quote the statement month when paying.");
  doc.setTextColor(0);

  doc.save(`statement-${(clinic?.name ?? "clinic").replace(/[^\w-]+/g, "-")}-${statement.month.slice(0, 7)}.pdf`);
}
