import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {transform} from 'esbuild';
let handler;let run=null;let providerCalls=0;let payloads=[];let fail=false;
const env={CASE_NOTIFY_SECRET:'fictional-secret',SUPABASE_URL:'https://example.test',SUPABASE_SERVICE_ROLE_KEY:'fictional',RESEND_API_KEY:'fictional'};
globalThis.Deno={env:{get:k=>env[k]},serve:fn=>{handler=fn;}};
const settings={enabled:true,recipient:'owner@example.test'};
const client={from(table){const builder={select(){return this;},eq(){return this;},order(){return this;},single:async()=>({data:settings,error:null}),maybeSingle:async()=>({data:run,error:null}),range:async()=>({data:table==='cases'?[{id:'fictional',clinic_id:'c',lab_id:'l',stage_index:0,created_at:new Date().toISOString(),history:[]}]:[{id:table==='labs'?'l':'c',name:'Example'}],error:null}),upsert:async(row)=>{run??={...row,sent_at:null};return {error:null};},update(row){Object.assign(run,row);return {eq:async()=>({error:null})};}};return builder;}};
globalThis.pickupTestClient=client;
const originalFetch=globalThis.fetch;
globalThis.fetch=async(url,options)=>{assert.equal(url,'https://api.resend.com/emails');providerCalls++;payloads.push({body:options.body,key:options.headers['Idempotency-Key']});return new Response('{}',{status:fail?500:200});};
let source=readFileSync(new URL('../supabase/functions/pickup-digest/index.ts',import.meta.url),'utf8').replace('import { createClient } from "jsr:@supabase/supabase-js@2";','const createClient=()=>globalThis.pickupTestClient;').replace('"../_shared/pickupMonitor.js"',JSON.stringify(new URL('../supabase/functions/_shared/pickupMonitor.js',import.meta.url).href));
source=(await transform(source,{loader:'ts',format:'esm'})).code;
await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'));
const request=secret=>new Request('https://example.test',{method:'POST',headers:{'x-webhook-secret':secret}});
assert.equal((await handler(request('wrong'))).status,401);assert.equal(providerCalls,0);
const secret=env.CASE_NOTIFY_SECRET;delete env.CASE_NOTIFY_SECRET;assert.equal((await handler(request(secret))).status,401);env.CASE_NOTIFY_SECRET=secret;
fail=true;assert.equal((await handler(request(secret))).status,500);assert.equal(run.sent_at,null);
fail=false;assert.equal((await handler(request(secret))).status,200);assert.ok(run.sent_at);assert.deepEqual(payloads[0],payloads[1],'retry uses identical persisted snapshot and idempotency key');
assert.equal((await handler(request(secret))).status,200);assert.equal(providerCalls,2,'already sent skips provider');
assert.ok(!JSON.parse(payloads[0].body).html.includes('patient_name'));
globalThis.fetch=originalFetch;console.log('Digest checks passed: secret gate, fail-closed configuration, failed-send retry, stable payload/key, daily deduplication.');
