import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {platformEmail} from '../supabase/functions/platform-digest/email.ts';
const {PGlite}=await import(process.env.PGLITE_MODULE||'@electric-sql/pglite');const db=new PGlite();
await db.exec(`create role anon;create role authenticated;create role service_role bypassrls;create schema auth;create schema private;create schema cron;create function cron.schedule(text,text,text) returns bigint language sql as $$select 1::bigint$$;
create table registration_review_settings(id boolean,recipient text);insert into registration_review_settings values(true,'reviewer@example.invalid');
create table auth.users(id uuid,created_at timestamptz);create table profiles(created_at timestamptz);create table clinics(created_at timestamptz);create table labs(created_at timestamptz);
create table cases(created_at timestamptz,updated_at timestamptz,lab_id uuid,stage_index int,cancel_status text,patient_name text);
create table case_rounds(created_at timestamptz,status text);create table clinic_invitations(created_at timestamptz);
create table login_events(user_id uuid,created_at timestamptz,action text,detail text);
create table client_errors(at timestamptz,user_id uuid,message text);
create table agent_runs(started_at timestamptz,outcome text,error text,shadow boolean);
create table registration_review_events(sent_at timestamptz,last_error text);
insert into auth.users values(null,'2026-09-13T19:00:00Z'),(null,'2026-09-14T19:00:00Z');
insert into cases values('2026-09-14T18:00:00Z','2026-09-14T18:00:00Z','00000000-0000-4000-8000-000000000001',0,'none','FICTIONAL_PRIVATE_NAME');
insert into client_errors values('2026-09-14T18:00:00Z',null,'TypeError FICTIONAL_PRIVATE_NAME'),('2026-09-14T18:01:00Z',null,'print FICTIONAL_PRIVATE_NAME');`);
await db.exec(readFileSync('supabase/migrations/20260914_platform_daily_digest.sql','utf8'));
let p=(await db.query("select platform_activity_summary('2026-09-13T19:00Z','2026-09-14T19:00Z') p")).rows[0].p;
assert.equal(p.new_users,1,'Half-open daily boundaries');assert.equal(p.cases_sent,1);assert.equal(p.client_errors,2);assert(!JSON.stringify(p).includes('FICTIONAL_PRIVATE_NAME'));
const mail=platformEmail('daily-2026-09-14',p);assert(!mail.html.includes('FICTIONAL_PRIVATE_NAME'));assert(mail.html.includes('Oman time'));assert(mail.html.includes('Application runtime: 1'));
assert.equal((await db.query('select * from claim_platform_digest()')).rows.length,0);
await db.exec("update platform_digest_settings set enabled=true,starts_at=now()-interval '2 days'");
let run=(await db.query('select * from claim_platform_digest()')).rows[0];assert(run);assert.equal(Date.parse(run.payload.window_end)-Date.parse(run.payload.window_start),86400000);assert.equal(new Date(run.payload.window_end).getUTCHours(),19);
assert.equal((await db.query('select * from claim_platform_digest()')).rows.length,0);
await db.exec("update platform_digest_runs set lease_until=now()-interval '1 minute'");assert.deepEqual((await db.query('select * from claim_platform_digest()')).rows[0].payload,run.payload);
await db.exec('update platform_digest_runs set sent_at=now()');assert.equal((await db.query('select * from claim_platform_digest()')).rows.length,0);
assert.equal((await db.query('select * from claim_platform_digest(true)')).rows.length,1,'Preview separate from nightly mail');
await db.exec('set role authenticated');await assert.rejects(db.query('select * from platform_digest_runs'),/permission denied/);await assert.rejects(db.query('select * from claim_platform_digest(true)'),/permission denied/);await db.exec('reset role');await db.close();
console.log('PASS: daily boundaries, Oman 23:00, no private text, counts, zero-activity report, switch, leases, stable retry, deduplication, preview isolation and permissions');
