import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {registrationEmail,acceptsSecret} from '../supabase/functions/registration-notify/email.ts';
const {PGlite}=await import(process.env.PGLITE_MODULE||'@electric-sql/pglite');const db=new PGlite();
await db.exec(`create role anon;create role authenticated;create role service_role bypassrls;create schema auth;create schema private;create schema cron;create function cron.schedule(text,text,text) returns bigint language sql as $$select 1::bigint$$;
create table auth.users(id uuid primary key,email text,created_at timestamptz default now(),email_confirmed_at timestamptz);
create table profiles(id uuid,role text,name text,phone text,clinic_id uuid,lab_id uuid);
create table clinics(id uuid,name text,email text,contact text,governorate text,wilayat text,status text default 'pending');
create table labs(like clinics including defaults);
insert into auth.users(id,email,created_at) values('00000000-0000-4000-8000-000000000001','owner@example.invalid',now()-interval '1 day');
insert into profiles(id,role) values('00000000-0000-4000-8000-000000000001','admin');
insert into clinics(id,status) values('00000000-0000-4000-8000-000000000010','suspended');`);
await db.exec("select set_config('app.registration_review_recipient','reviewer@example.invalid',false)");
await db.exec(readFileSync('supabase/migrations/20260914_registration_review_queue.sql','utf8'));
assert.equal((await db.query('select * from claim_registration_reviews()')).rows.length,0);
await db.exec('update registration_review_settings set enabled=true');
assert.equal((await db.query('select * from claim_registration_reviews()')).rows.length,0,'No historical signup emails');
await db.exec(`insert into auth.users(id,email) values('00000000-0000-4000-8000-000000000002','new@example.invalid')`);
const first=(await db.query('select * from claim_registration_reviews()')).rows;assert.equal(first.length,1);assert.equal(first[0].kind,'signup');
assert.equal((await db.query('select * from claim_registration_reviews()')).rows.length,0,'Lease prevents duplicate workers');
await db.exec(`update registration_review_events set lease_until=now()-interval '1 minute'`);
assert.equal((await db.query('select * from claim_registration_reviews()')).rows[0].id,first[0].id,'Retry retains idempotency key and snapshot');
await db.exec(`update registration_review_events set sent_at=now();insert into profiles(id,role,name) values('00000000-0000-4000-8000-000000000002','dentist','Fictional Dentist')`);
assert.equal((await db.query('select * from claim_registration_reviews()')).rows[0].kind,'setup');
await db.exec('set role authenticated');await assert.rejects(db.query('select * from registration_review_events'),/permission denied/);await assert.rejects(db.query('select * from claim_registration_reviews()'),/permission denied/);await db.exec('reset role');
await db.exec(readFileSync('supabase/migrations/20260914_registration_immediate_access.sql','utf8'));
await db.exec(`insert into clinics(id) values('00000000-0000-4000-8000-000000000011');insert into labs(id) values('00000000-0000-4000-8000-000000000012')`);
assert.equal((await db.query("select status from clinics where id='00000000-0000-4000-8000-000000000011'")).rows[0].status,'active');
assert.equal((await db.query('select status from labs')).rows[0].status,'active');
assert.equal((await db.query("select status from clinics where id='00000000-0000-4000-8000-000000000010'")).rows[0].status,'suspended');
const mail=registrationEmail('setup',{name:'<script>bad</script>',email:'fictional@example.invalid'});assert(!mail.html.includes('<script>'));assert(mail.html.includes('&lt;script&gt;'));assert(!mail.subject.includes('fictional'));
assert(!acceptsSecret(null,undefined));assert(!acceptsSecret('x','y'));assert(acceptsSecret('test','test'));
await db.close();console.log('PASS: queue, retries, deduplication, privacy, no historic backfill, new active orgs, preserved suspension, email escaping and auth gate');
