import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
const {PGlite}=await import(process.env.PGLITE_MODULE || '@electric-sql/pglite');
const db=new PGlite();
const lab='00000000-0000-4000-8000-000000000001',other='00000000-0000-4000-8000-000000000002',user='00000000-0000-4000-8000-000000000003';
await db.exec(`
create role anon;create role authenticated;create role service_role;
create schema auth;grant usage on schema auth to authenticated,anon;
create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('test.user',true),'')::uuid $$;
create function my_lab_id() returns uuid language sql stable as $$ select nullif(current_setting('test.lab',true),'')::uuid $$;
create function is_admin() returns boolean language sql stable as $$ select current_setting('test.role',true)='superadmin' $$;
create function is_lab_admin() returns boolean language sql stable as $$ select current_setting('test.role',true)='admin' $$;
create function is_lab_accountant() returns boolean language sql stable as $$ select current_setting('test.role',true)='accountant' $$;
create function is_lab_finance() returns boolean language sql stable as $$ select is_lab_admin() or is_lab_accountant() $$;
create table labs(id uuid primary key,finance_history_before date);
create table lab_members(user_id uuid,lab_id uuid,role text,status text);
create table clinic_statements(id uuid primary key default gen_random_uuid(),lab_id uuid,clinic_id uuid,clinic_name text,month date,total numeric,status text,line_items jsonb default '[]',kind text default 'work');
create table lab_payments(id uuid primary key default gen_random_uuid(),statement_id uuid,voided_at timestamptz);
create table cases(id text primary key,lab_id uuid,invoice_number text);
alter table clinic_statements enable row level security;
grant select,insert,update,delete on clinic_statements to authenticated;
create policy finance_select on clinic_statements for select using (lab_id=my_lab_id() and is_lab_finance());
create policy finance_insert on clinic_statements for insert with check(lab_id=my_lab_id() and is_lab_finance());
create policy finance_update on clinic_statements for update using(lab_id=my_lab_id() and is_lab_finance());
create policy finance_delete on clinic_statements for delete using(lab_id=my_lab_id() and is_lab_finance());
insert into labs values('${lab}',null),('${other}',null);
insert into lab_members values('${user}','${lab}','lab_tech','active');
select set_config('test.user','${user}',false),set_config('test.lab','${lab}',false),set_config('test.role','tech',false);
`);
const sql=readFileSync(new URL('../supabase/migrations/20260910_work_ledger.sql',import.meta.url),'utf8');
await db.exec(sql);await db.exec(sql);
const id='00000000-0000-4000-8000-000000000004';
const entry={clinicName:'Example Clinic',date:'2026-09-01',invoice:'PAPER-1',patient:'Fictional Patient',dentist:'Example Doctor',procedure:'Crown',units:'2',price:'10.125'};
const save=(id,rev,e)=>db.query('select save_manual_lab_work($1,$2,$3)',[id,rev,JSON.stringify(e)]);
const scalar=async(q)=>Object.values((await db.query(q)).rows[0])[0];
await db.exec('set role authenticated');
await save(id,null,entry);await save(id,null,entry);
assert.equal(await scalar('select count(*)::int from manual_lab_work'),1,'retry idempotent');
assert.equal(await scalar('select count(*)::int from clinic_statements'),0,'tech cannot read financial statements');
await assert.rejects(db.exec(`update manual_lab_work set revision=9`),/permission denied/);
await db.exec('reset role');
assert.equal(Number(await scalar('select total from clinic_statements')),20.25);
await db.exec('set role authenticated');
await save(id,1,{...entry,price:'12'});
await assert.rejects(save(id,1,{...entry,price:'13'}),/changed/);
await assert.rejects(save('00000000-0000-4000-8000-000000000005',null,entry),/already exists/);
await assert.rejects(save('00000000-0000-4000-8000-000000000006',null,{...entry,invoice:'PAPER-2',date:'2026-08-31'}),/Enter a clinic/);
await assert.rejects(save('00000000-0000-4000-8000-000000000006',null,{...entry,invoice:'PAPER-2',units:'-1'}),/Enter a clinic/);
await db.exec(`reset role;select set_config('test.role','accountant',false);set role authenticated;`);
await assert.rejects(db.exec('update clinic_statements set total=1'),/All Work/);
await assert.rejects(db.exec('delete from clinic_statements'),/retained/);
await db.exec("update clinic_statements set status='paid'");
await assert.rejects(save(id,2,{...entry,price:'15'}),/payment/);
await db.exec("update clinic_statements set status='unpaid'");
await assert.rejects(db.query(`insert into clinic_statements(lab_id,clinic_name,month,total,status,line_items) values($1,'Example Clinic','2026-09-01',5,'unpaid',$2)`,[lab,JSON.stringify([{invoice:'PAPER-1'}])]),/already exists/);
await assert.rejects(db.query(`insert into clinic_statements(lab_id,clinic_name,month,total,status) values($1,'Example Clinic','2026-09-01',5,'unpaid')`,[lab]),/already entered/);
await db.exec(`reset role;insert into cases values('C-FICTION','${lab}','DIGITAL-1');set role authenticated;`);
await assert.rejects(save('00000000-0000-4000-8000-000000000006',null,{...entry,invoice:'DIGITAL-1'}),/already exists/);
assert.equal(await scalar('select count(*)::int from manual_lab_work_audit'),2,'edits retained');
await db.exec('reset role');
await assert.rejects(db.query('insert into cases values($1,$2,$3)',['C-DUPLICATE',lab,'PAPER-1']),/already exists in paper/);
await db.query(`insert into clinic_statements(lab_id,clinic_name,month,total,status) values($1,'Other Example Clinic','2026-09-01',100,'unpaid')`,[lab]);
await db.exec('set role authenticated');
await assert.rejects(save('00000000-0000-4000-8000-000000000006',null,{...entry,clinicName:'Other Example Clinic',invoice:'PAPER-3'}),/totals-only/);

await db.exec(`reset role;select set_config('test.lab','${other}',false);set role authenticated;`);
assert.equal(await scalar('select count(*)::int from manual_lab_work'),0);
await assert.rejects(save(id,2,{...entry,price:'16'}),/access denied/);
await db.exec(`reset role;select set_config('test.lab','',false);set role authenticated;`);
await assert.rejects(save(id,2,entry),/Only active lab/);
await db.exec('reset role;set role anon');
await assert.rejects(save(id,null,entry),/permission denied/);
await db.close();
console.log('Work ledger database checks passed: migration rerun, tech save, no finance access, idempotency, amount, audit, stale edit, duplicates, paid edits, cross-lab and anonymous denial.');
