const number=(v:unknown)=>Number.isFinite(Number(v))?Math.max(0,Math.trunc(Number(v))):0;
export function platformEmail(id:string,p:Record<string,any>){
 const date=(v:unknown)=>new Date(String(v)).toLocaleString('en-GB',{timeZone:'Asia/Muscat',day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit',hour12:true});
 const row=(label:string,key:string)=>`<tr><td style="padding:7px 16px 7px 0;color:#475569">${label}</td><td style="padding:7px 0;text-align:right;font-weight:bold">${number(p[key])}</td></tr>`;
 const section=(title:string,fields:string[][])=>`<h2 style="font-size:17px;margin:26px 0 8px;color:#1d4ed8">${title}</h2><table width="100%" style="border-collapse:collapse;font-size:14px">${fields.map(([label,key])=>row(label,key)).join('')}</table>`;
 const preview=id.startsWith('preview-');
 const groups=[['Printing','Printing'],['Connection / loading','Connection / loading'],['Application runtime','Application runtime'],['Other recorded errors','Other recorded errors']];
 const categories=groups.filter(([,key])=>number(p.error_categories?.[key])>0).map(([label,key])=>`<li>${label}: ${number(p.error_categories[key])}</li>`).join('');
 return {subject:`Dr-Crown — ${preview?'preview: ':''}daily platform summary`,html:`<div style="background:#f1f5f9;padding:24px 12px;font-family:Arial,sans-serif;color:#0f172a"><div style="max-width:580px;margin:auto;background:white;padding:28px;border-radius:12px"><h1 style="font-size:25px;color:#1d4ed8;margin:0">Dr-Crown</h1><h2 style="font-size:21px">${preview?'Summary preview':'Daily platform summary'}</h2><p style="font-size:13px;color:#64748b">${date(p.window_start)} → ${date(p.window_end)}<br>Oman time · Previous 24 hours</p><p>${number(p.client_errors)>0||number(p.noor_failures)>0||number(p.registration_emails_failed)>0?'Recorded issues need review; see the counts below.':'No client errors, Noor failures or outstanding registration-mail failures were recorded in these checks.'}</p>
${section('Registration & onboarding',[['New user accounts','new_users'],['Users completing profile setup','new_profiles'],['New clinics','new_clinics'],['New labs / lab records','new_labs'],['Clinic invitations created','invites_created']])}
${section('Cases & recorded work',[['New cases sent to labs','cases_sent'],['Cases created or updated','cases_updated'],['New follow-up rounds','followups_created'],['Recorded stage advances','stage_advances'],['Recorded stage reversals','stage_reversals']])}
${section('Platform usage',[['Users with recorded activity','active_users'],['Recorded sign-ins','signins'],['Print sheets opened','print_views'],['Other recorded actions','other_activity']])}
${section('Errors & automation',[['Client error reports','client_errors'],['Identified users with errors','users_with_errors'],['Noor runs','noor_runs'],['Noor runs in shadow mode','noor_shadow_runs'],['Noor failed runs','noor_failures'],['Registration emails accepted by provider','registration_emails_sent'],['Unsent registration emails with failures','registration_emails_failed']])}
${categories?`<ul style="font-size:13px;color:#475569">${categories}</ul>`:''}
${section('Open work at report capture',[['Cases awaiting pickup','waiting_pickup'],['Awaiting pickup over 24 hours','waiting_over_day'],['Open follow-up rounds','open_followups']])}
<p style="font-size:12px;color:#64748b;line-height:20px">Counts only—no patient names, user names, case details or raw error messages. Activity logs reflect recorded actions, not a complete audit of every interaction. Print-sheet opens do not prove printing succeeded. Backend errors outside the tracked logs, offline failures and unreported user difficulties may not appear. Pickup age includes nights and weekends.</p><p><a href="https://dr-crown.com/" style="color:#1d4ed8;font-weight:bold">Open Dr-Crown</a></p></div></div>`};
}
